[project]
name = "progres-socket"
version = "0.0.0"
description = "Desktop app for sharing files through socket."
readme = "README.MD"
requires-python = ">=3.13"

[tool.pyside6-project]
files = [
    "main.py",
    "app/ui/main.ui"
]
