# Form implementation generated from reading ui file 'app/ui/main.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(460, 100, 86, 26))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuTest = QtWidgets.QMenu(parent=self.menubar)
        self.menuTest.setObjectName("menuTest")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLeka = QtGui.QAction(parent=MainWindow)
        self.actionLeka.setObjectName("actionLeka")
        self.actionMerde = QtGui.QAction(parent=MainWindow)
        self.actionMerde.setObjectName("actionMerde")
        self.actionOka = QtGui.QAction(parent=MainWindow)
        self.actionOka.setObjectName("actionOka")
        self.actionKos = QtGui.QAction(parent=MainWindow)
        self.actionKos.setObjectName("actionKos")
        self.menuTest.addAction(self.actionLeka)
        self.menuTest.addAction(self.actionMerde)
        self.menuTest.addSeparator()
        self.menuTest.addAction(self.actionOka)
        self.menuTest.addAction(self.actionKos)
        self.menubar.addAction(self.menuTest.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.menuTest.setTitle(_translate("MainWindow", "Test"))
        self.actionLeka.setText(_translate("MainWindow", "Leka"))
        self.actionMerde.setText(_translate("MainWindow", "Merde"))
        self.actionOka.setText(_translate("MainWindow", "Oka"))
        self.actionKos.setText(_translate("MainWindow", "Kosa"))
